### PR TITLE
Add possibility to analyze maven modules as projects

### PR DESCRIPTION
**Pull request by tobiasstadler**
Added the possibility to analyze maven modules as toplevel instead subprojects

### CODE REVIEW

**Comment by henryju** [comment]
Hi, we are about to change deeply how the scanner works, by replacing modules by folders in SonarQube server side. The use case of analyzing each Maven module as project is not very frequent, so in the past we always rejected it. Maybe we could reconsider after the big refactoring is done.
All that to say, donc expect this PR to merged in short term.

As a general note, it is missing tests :)

**Comment by tobiasstadler** [comment]
@henryju Thank you for your answer. Do you have any timeline for the folders stuff?

**Comment by henryju** [comment]
I'm closing this PR since the proposed feature is not something we want to implement/maintain currently. Feel free to open a thread on our community forum to see opinion of others.

**Comment by YannLeCorse** [comment]
We have exactly the same need. We have a huge project with 1000+ sub modules and obviously we want to have a dedicated page per module rather than consolidating everything in 1 place…
Having the default behaviour and an option to switch to this mode would be very nice.

Thanks a lot for the PR ;)

**Comment by henryju** [comment]
> obviously we want to have a dedicated page per module

Do you really expect people to look at dashboard of each 1000+ modules, to track numbers?

**Comment by YannLeCorse** [comment]
Yes... We have plugins for high level view per teams but we also look at the quality trend per module.
Even with a small project, be able to configure how we consider the modules (consolidated view or detailed one) would be a good option.
FYI, we started discussion with our SonarQube support in parallel.

**Pull request closed without merging**
